# Generated by Django 3.0.8 on 2020-07-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1', models.IntegerField(unique=True)),
                ('user_id', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('birthday', models.DateField(null=True)),
                ('picture', models.ImageField(default='no-avatar.png', upload_to='pic_files')),
                ('status', models.CharField(blank=True, choices=[('P', 'P'), ('L', 'L'), ('A', 'A')], max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
