# Generated by Django 3.0.8 on 2020-07-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfmc', '0003_auto_20200724_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='t2',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='t3',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='t4',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='t5',
            field=models.IntegerField(unique=True),
        ),
    ]
