# Generated by Django 3.0.8 on 2020-07-24 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfmc', '0004_auto_20200724_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='logbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oras', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.CharField(choices=[('I', 'In'), ('O', 'Out')], max_length=1)),
                ('employee', models.ForeignKey(db_column='t1', on_delete=django.db.models.deletion.CASCADE, to='cfmc.employee', to_field='t1')),
            ],
            options={
                'verbose_name_plural': 'Logbox',
            },
        ),
    ]
