# Generated by Django 3.0.8 on 2020-07-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfmc', '0005_logbox'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logbox',
            old_name='oras',
            new_name='date_time',
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'PRESENT'), ('L', 'LATE'), ('A', 'ABSENT')], max_length=5),
        ),
        migrations.AlterField(
            model_name='logbox',
            name='transaction',
            field=models.CharField(choices=[('I', 'IN'), ('O', 'OUT')], max_length=1),
        ),
    ]
