# Generated by Django 3.0.8 on 2020-07-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfmc', '0006_auto_20200724_0833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'PRESENT'), ('A', 'ABSENT')], max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('t1', 't2', 't3', 't4', 't5')},
        ),
    ]
