# Generated by Django 3.0.8 on 2020-07-30 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfmc', '0008_auto_20200730_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'Employees'},
        ),
        migrations.RemoveConstraint(
            model_name='employee',
            name='name of constraint',
        ),
    ]
