# Generated by Django 3.0.8 on 2020-07-30 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfmc', '0009_auto_20200730_1033'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('t1', 't2', 't3', 't4', 't5')},
        ),
    ]
