# Generated by Django 3.0.8 on 2020-07-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfmc', '0012_auto_20200730_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='t2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='t3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='t4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='t5',
            field=models.IntegerField(),
        ),
    ]
