# Generated by Django 3.0.8 on 2020-07-30 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfmc', '0015_auto_20200730_1100'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employee',
            name='name of constraint',
        ),
    ]
