# Generated by Django 3.0.8 on 2020-07-30 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfmc', '0017_auto_20200730_1116'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('t5', 't4', 't3', 't2')},
        ),
    ]
