# Generated by Django 3.0.8 on 2020-07-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfmc', '0020_auto_20200730_1140'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set(),
        ),
    ]
