# Generated by Django 3.1.7 on 2021-03-22 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfmc', '0021_auto_20200730_1149'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('t1', 't2', 't3', 't4', 't5')},
        ),
    ]
