# Generated by Django 3.0.7 on 2021-03-22 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfmc', '0022_auto_20210322_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='logbox',
            name='employee',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='cfmc.employee', to_field='user_id'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='t1',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='t2',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='t3',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='t4',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='t5',
        ),
    ]
