# Generated by Django 3.0.7 on 2021-03-22 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfmc', '0023_auto_20210322_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='picture',
            field=models.ImageField(default='no-avatar.jpg', upload_to='content_file_name'),
        ),
        migrations.AlterField(
            model_name='logbox',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfmc.employee'),
        ),
    ]
