# Generated by Django 3.0.7 on 2021-03-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfmc', '0026_auto_20210324_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='picture1',
            field=models.ImageField(upload_to='content_file_name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='picture2',
            field=models.ImageField(upload_to='content_file_name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='picture3',
            field=models.ImageField(upload_to='content_file_name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='picture4',
            field=models.ImageField(upload_to='content_file_name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='picture5',
            field=models.ImageField(upload_to='content_file_name'),
        ),
    ]
