# Generated by Django 3.0.7 on 2021-03-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfmc', '0028_auto_20210324_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='picture2',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='picture3',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='picture4',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='picture5',
        ),
    ]
