# Generated by Django 3.0.7 on 2021-03-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfmc', '0029_auto_20210324_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='picture2',
            field=models.ImageField(default='', upload_to='content_file_name2'),
        ),
        migrations.AddField(
            model_name='employee',
            name='picture3',
            field=models.ImageField(default='', upload_to='content_file_name3'),
        ),
        migrations.AddField(
            model_name='employee',
            name='picture4',
            field=models.ImageField(default='', upload_to='content_file_name4'),
        ),
        migrations.AddField(
            model_name='employee',
            name='picture5',
            field=models.ImageField(default='', upload_to='content_file_name5'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='picture1',
            field=models.ImageField(default='', upload_to='content_file_name1'),
        ),
    ]
