# Generated by Django 3.0.8 on 2020-07-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '1. Jul 26, 2020 - Aug 01, 2020',
            },
        ),
        migrations.CreateModel(
            name='Las2Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '3. Jul 12, 2020 - Jul 18, 2020',
            },
        ),
        migrations.CreateModel(
            name='Las3Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '4. Jul 05, 2020 - Jul 11, 2020',
            },
        ),
        migrations.CreateModel(
            name='LasWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '2.  Jul 19, 2020 - Jul 25, 2020',
            },
        ),
    ]
