# Generated by Django 3.1.7 on 2021-03-22 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curweek',
            options={'verbose_name_plural': '1. Mar 21, 2021 - Mar 27, 2021'},
        ),
        migrations.AlterModelOptions(
            name='las2week',
            options={'verbose_name_plural': '3. Mar 07, 2021 - Mar 13, 2021'},
        ),
        migrations.AlterModelOptions(
            name='las3week',
            options={'verbose_name_plural': '4. Feb 28, 2021 - Mar 06, 2021'},
        ),
        migrations.AlterModelOptions(
            name='lasweek',
            options={'verbose_name_plural': '2.  Mar 14, 2021 - Mar 20, 2021'},
        ),
    ]
