# Generated by Django 3.0.7 on 2021-06-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20210322_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '5. Validations',
            },
        ),
        migrations.AlterModelOptions(
            name='curweek',
            options={'verbose_name_plural': '1. May 30, 2021 - Jun 05, 2021'},
        ),
        migrations.AlterModelOptions(
            name='las2week',
            options={'verbose_name_plural': '3. May 16, 2021 - May 22, 2021'},
        ),
        migrations.AlterModelOptions(
            name='las3week',
            options={'verbose_name_plural': '4. May 09, 2021 - May 15, 2021'},
        ),
        migrations.AlterModelOptions(
            name='lasweek',
            options={'verbose_name_plural': '2.  May 23, 2021 - May 29, 2021'},
        ),
    ]
